# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
- group: Docs Creds

resources:
  repositories:
  - repository: v2-docs
    type: github
    name: griddbnet/v2-docs
    endpoint: github.com_Imisrael
    ref: main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- checkout: self
  path: "main"
  displayName: 'checkout self'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      home=$(Pipeline.Workspace)
      npm add -D vitepress
      npm install
      npm run docs:build

- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: $(ftp_url)
    username: $(ftp_username)
    password: $(ftp_password)
    rootDirectory: '/home/vsts/work/1/main/.vitepress/dist/'
    filePatterns: '**'
    remoteDirectory: '/site/wwwroot/'
    clean: false
    cleanContents: true
    preservePaths: true
    trustSSL: false